siesta: siesta_ortho siesta_ice siesta_hm_lda siesta_hm_gga
	
siesta_ortho:
	@cd siesta/; sh run_ortho.sh; cd ..

siesta_hm_lda:
	@cd siesta/; sh run_ortho_hm_lda.sh; cd ..
	
siesta_hm_gga:
	@cd siesta/; sh run_ortho_hm_gga.sh; cd ..

siesta_ice:
	@cd siesta/; sh run_ice.sh; cd ..



